extends RefCounted
## Oklab must agree with tokencollider/oklab.py. The expected values here were produced
## by the Python side; if either drifts, a picked colour stops selecting the
## point the user aimed at, and nothing else in the app would notice.
const Oklab := preload("res://lib/Oklab.gd")

var harness

func test_matches_python_on_every_fixture_colour() -> void:
	## Cross-language check against tokencollider/oklab.py. The fixture is generated by
	## the Python: for a grid of z-scores it renders the colour the sidecar
	## would paint, reads it back, and clamps to the displayable range, which
	## is what the viewport does. Anything else compares two different
	## contracts and calls the difference a bug.
	##
	## Note the two sides are NOT plain inverses. hex_to_zscores is documented
	## as the inverse "within gamut" only; the corners of the z-cube fall
	## outside sRGB and clip, and Python does not clamp on the way back while
	## the viewport does. Both are deliberate.
	var f := FileAccess.open("res://tests/oklab_truth.json", FileAccess.READ)
	harness.ok(f != null, "fixture present")
	if f == null:
		return
	var rows: Array = JSON.parse_string(f.get_as_text())
	harness.ok(rows.size() > 20, "fixture has rows")
	var worst := 0.0
	for row in rows:
		var got := Oklab.color_to_zscores(Color(row["hex"]))
		var want: Array = row["z"]
		worst = maxf(worst, absf(got.x - want[0]))
		worst = maxf(worst, absf(got.y - want[1]))
		worst = maxf(worst, absf(got.z - want[2]))
	harness.close(worst, 0.0, 1e-4, "max disagreement with tokencollider/oklab.py")


func test_known_colours() -> void:
	# Pure white: Oklab L = 1, a = b = 0.
	var w := Oklab.srgb_to_oklab(Color(1, 1, 1))
	harness.close(w.x, 1.0, 1e-4, "white L")
	harness.close(w.y, 0.0, 1e-4, "white a")
	harness.close(w.z, 0.0, 1e-4, "white b")
	# Pure black: all zero.
	var k := Oklab.srgb_to_oklab(Color(0, 0, 0))
	harness.close(k.x, 0.0, 1e-6, "black L")

func test_linearisation_branch() -> void:
	# The sRGB transfer function is piecewise; both sides must be exercised.
	harness.close(Oklab.srgb_to_linear(0.0), 0.0, 1e-9, "linear at 0")
	harness.close(Oklab.srgb_to_linear(0.04), 0.04 / 12.92, 1e-9, "linear branch")
	harness.close(Oklab.srgb_to_linear(1.0), 1.0, 1e-9, "gamma branch at 1")

func test_zscores_clamp_and_centre() -> void:
	# White is far above L_CENTER, so it must clamp rather than run away.
	var z := Oklab.color_to_zscores(Color(1, 1, 1))
	harness.eq(z.x, Oklab.Z_CLAMP, "white clamps to +Z")
	# A grey at exactly L_CENTER lands at z = 0 on the lightness axis.
	var lo := 0.0
	var hi := 1.0
	for i in 60:
		var mid := (lo + hi) * 0.5
		if Oklab.srgb_to_oklab(Color(mid, mid, mid)).x < Oklab.L_CENTER:
			lo = mid
		else:
			hi = mid
	var neutral := Oklab.color_to_zscores(Color(lo, lo, lo))
	harness.close(neutral.x, 0.0, 1e-3, "L_CENTER grey is z=0")
	harness.close(neutral.y, 0.0, 1e-6, "grey has no a")
	harness.close(neutral.z, 0.0, 1e-6, "grey has no b")
